language: java
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
  
script: 
  - mvn install -DskipTests=false
  - mvn test
  

services: mysql

before_script:
  - mysql -e 'create database projetobd;'
