language: java
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
  
script: 
  - mvn install -DskipTests=false
  - mvn test
  
services: mysql


before_script:
  - mysql -e 'CREATE DATABASE projetobd;'
  - mysql -e 'SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;'
  - mysql -e 'SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;'
  - mysql -e "SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';"
  - mysql -e 'DROP DATABASE IF EXISTS projetobd ;'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS projetobd DEFAULT CHARACTER SET utf8 ;'
  - mysql -e 'SHOW WARNINGS;'
  - mysql -e 'USE projetobd;DROP TABLE IF EXISTS gerente;'
  - mysql -e 'SHOW WARNINGS;'
  - mysql -e 'USE projetobd;CREATE  TABLE IF NOT EXISTS gerente (Login VARCHAR(45) NOT NULL ,Senha VARCHAR(45) NULL , PRIMARY KEY (Login) ) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;'
  - mysql -e 'SHOW WARNINGS;'
  - mysql -e 'USE projetobd;CREATE UNIQUE INDEX Login_UNIQUE ON gerente (Login ASC) ;'
  - mysql -e 'SHOW WARNINGS;'
  - mysql -e 'USE projetobd;DROP TABLE IF EXISTS pessoa;'
  - mysql -e 'SHOW WARNINGS;'
  - mysql -e "USE projetobd;CREATE  TABLE IF NOT EXISTS pessoa (id INT NOT NULL AUTO_INCREMENT ,CPF VARCHAR(45) NOT NULL ,gerente_Login VARCHAR(45) NULL DEFAULT NULL ,PNome VARCHAR(45) NOT NULL ,RG INT(11) NULL ,Rua VARCHAR(45) NULL ,Numero INT(11) NULL ,Bairro VARCHAR(45) NULL ,CEP VARCHAR(45) NULL ,TipoPessoa ENUM('CLIENTE','MONITOR','GERENTE') NOT NULL ,Telefone VARCHAR(45) NOT NULL ,Cidade VARCHAR(45) NULL ,PRIMARY KEY (id) ) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;"

  - mysql -e 'USE projetobd;DROP TABLE IF EXISTS tema;'
  - mysql -e 'SHOW WARNINGS;'
  - mysql -e 'USE projetobd;CREATE  TABLE IF NOT EXISTS tema (IdTema VARCHAR(45) NOT NULL ,Tnome VARCHAR(45) NOT NULL ,PRIMARY KEY (IdTema) )ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;'
  - mysql -e 'SHOW WARNINGS;'

  - mysql -e 'USE projetobd;DROP TABLE IF EXISTS pacote;'
  - mysql -e 'SHOW WARNINGS;'
  - mysql -e 'USE projetobd;CREATE  TABLE IF NOT EXISTS pacote (IdPacote VARCHAR(45) NOT NULL ,NomePacote VARCHAR(45) NOT NULL ,PrecoPacote DOUBLE NOT NULL ,PRIMARY KEY (IdPacote) ) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;'
  - mysql -e 'SHOW WARNINGS;'

  - mysql -e 'USE projetobd;DROP TABLE IF EXISTS localizacao;'
  - mysql -e 'SHOW WARNINGS;'
  - mysql -e 'USE projetobd;CREATE  TABLE IF NOT EXISTS localizacao (IdLocalizacao VARCHAR(45) NOT NULL ,CEP VARCHAR(45) NOT NULL ,Numero INT(11) NOT NULL ,Rua VARCHAR(45) NOT NULL ,Bairro VARCHAR(45) NOT NULL ,Cidade VARCHAR(45) NOT NULL ,PRIMARY KEY (IdLocalizacao) ) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;'
  - mysql -e 'SHOW WARNINGS;'

  - mysql -e 'USE projetobd;DROP TABLE IF EXISTS festa;'

  - mysql -e 'SHOW WARNINGS;'
  - mysql -e 'USE projetobd;CREATE  TABLE IF NOT EXISTS festa (IDFesta INT NOT NULL AUTO_INCREMENT , clienteCPF VARCHAR(45) NOT NULL , IdTema VARCHAR(45) NOT NULL , localizacaoCEP VARCHAR(45) NOT NULL , IdPacote VARCHAR(45) NOT NULL , DataInicio DATETIME NOT NULL , DataFIm DATETIME NULL , HoraInicio TIME NOT NULL , Externo TINYINT(1) NULL , QuantidadeConvidados INT(11) NOT NULL , EstiloFesta VARCHAR(45) NOT NULL , PRIMARY KEY (IDFesta) ) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8 PACK_KEYS = DEFAULT;'

  - mysql -e 'SHOW WARNINGS;'

  - mysql -e 'USE projetobd;DROP TABLE IF EXISTS item'

  - mysql -e 'USE projetobd;CREATE  TABLE IF NOT EXISTS item (IDItem VARCHAR(45) NOT NULL , NomeItem VARCHAR(45) NOT NULL ,QuantidadeTotal INT(11) NOT NULL , PrecoUnidade DOUBLE NOT NULL , PRIMARY KEY (IDItem) ) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;'

  - mysql -e 'SHOW WARNINGS;'

  - mysql -e  'USE projetobd;DROP TABLE IF EXISTS pessoa_monitora_item ;'
  - mysql -e 'SHOW WARNINGS;'
  - mysql -e 'USE projetobd;CREATE TABLE IF NOT EXISTS pessoa_monitora_item (pessoa_CPF VARCHAR(45) NOT NULL , item_IDItem INT NOT NULL , PRIMARY KEY (pessoa_CPF, item_IDItem) ) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;'

  - mysql -e 'SHOW WARNINGS;'

  - mysql -e 'USE projetobd;DROP TABLE IF EXISTS pacote_contem_item ;'
  - mysql -e 'SHOW WARNINGS;'
  - mysql -e 'USE projetobd;CREATE  TABLE IF NOT EXISTS pacote_contem_item (chavePacote VARCHAR(45) NOT NULL ,chaveItem VARCHAR(45) NOT NULL ,nomePacote VARCHAR(45) NOT NULL ,PRIMARY KEY (chavePacote, chaveItem) ) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;'

  - mysql -e 'SHOW WARNINGS;'
  - mysql -e 'USE projetobd;'
  
  
  - mysql -e 'USE projetobd;SELECT * FROM pacote_contem_item;' 
  - mysql -e 'USE projetobd;SELECT * FROM pacote WHERE nomePacote LIKE "pacote 23";'
  - mysql -e 'USE projetobd;SELECT * FROM pessoa;'
  - mysql -e 'USE projetobd;INSERT INTO pessoa VALUES(33, 90345566, null, "Marcos Cesar", 9876, "Rua do Meio", 89, "Lagoa Nova", 59076400, "CLIENTE", 99898932, "Natal");'
  - mysql -e 'USE projetobd;INSERT INTO pessoa VALUES(21, 21346655, null, "Joao Vinaud", 376, "Rua Maracajau", 8, "ponta Negra", 59090543, "CLIENTE", 988898911, "Parnamirim");'
  - mysql -e 'USE projetobd;INSERT INTO pessoa VALUES(12, 556699999, "josiel1nico", "Josiel Silva", 760000, "Rua Muriui", 67, "Lagoa Nova", 59076410, "GERENTE", 88442084, "Natal");'
  - mysql -e 'USE projetobd;SELECT * FROM gerente;'
  - mysql -e 'USE projetobd;SELECT * FROM pacote_contem_item;'
  - mysql -e 'USE projetobd;INSERT INTO pacote VALUES(50, "pacote Basico", 120);'
  - mysql -e 'USE projetobd;INSERT INTO pacote VALUES(11, "pacote Intermediario", 400);'
  - mysql -e 'USE projetobd;INSERT INTO pacote VALUES(12, "pacote Completo", 140);'
  - mysql -e 'USE projetobd;INSERT INTO pacote VALUES(13,"pacote VIP", 900);'
  - mysql -e 'USE projetobd;SELECT * FROM localizacao;'

  - mysql -e 'USE projetobd;INSERT INTO localizacao VALUES("10","51000000", 90, "Rua Carmosina", "Santo Antonio", "Mossoro");'
  - mysql -e 'USE projetobd;INSERT INTO localizacao VALUES("11","50000000", 158, "Rua Padre Cicero", "Acaua", "Mossoro");'
  - mysql -e 'USE projetobd;INSERT INTO localizacao VALUES("12","59210343", 30, "Rua do Meio", "Rocas", "Natal");'
  - mysql -e 'USE projetobd;INSERT INTO localizacao VALUES("13","59000212", 9, "Rua Mossoro", "Centro", "Assu");'
  
  
  - mysql -e 'USE projetobd;SELECT * FROM item;'
  - mysql -e "USE projetobd;INSERT INTO item VALUES('9090','Pula-pula', 3, 80);"
  - mysql -e "USE projetobd;INSERT INTO item VALUES('123','Cama elastica', 2, 100);"
  - mysql -e "USE projetobd;INSERT INTO item VALUES('GIF','Escorrego', 2, 50);"
  - mysql -e "USE projetobd;INSERT INTO item VALUES('12','Algodao doce', 1, 60);"

  - mysql -e 'USE projetobd;SELECT * FROM tema;'
  - mysql -e "USE projetobd;INSERT INTO tema VALUES('21','Pica-pau');"
  - mysql -e "USE projetobd;INSERT INTO tema VALUES('43','Moranguinho');"
  - mysql -e "USE projetobd;INSERT INTO tema VALUES('41','Meninas Super Poderosas');"
  - mysql -e "USE projetobd;INSERT INTO tema VALUES('90','Ben 10');"
  - mysql -e "USE projetobd;INSERT INTO tema VALUES('10','Cinderela');"

  - mysql -e "USE projetobd;DELETE FROM tema WHERE idTema = '5';"
  - mysql -e 'USE projetobd;DELETE FROM pacote;'
  - mysql -e 'USE projetobd;DESCRIBE festa;'
  - mysql -e 'USE projetobd;SELECT * FROM item;'
  - mysql -e "USE projetobd;SELECT * FROM item WHERE IdItem LIKE  'MFcl';"
  - mysql -e 'USE projetobd;SELECT * FROM pacote_contem_item;'
  - mysql -e 'USE projetobd;SELECT * FROM pessoa;'
  - mysql -e 'USE projetobd;SELECT * FROM festa;'
  - mysql -e 'USE projetobd;SELECT * FROM festa;'
  - mysql -e 'USE projetobd;DESCRIBE festa;'
  
