language: java
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
  
script: 
  - mvn install -DskipTests=false
  - mvn test

services: mysql

before_script:
  - mysql -e 'create database projetobd;
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

DROP SCHEMA IF EXISTS `projetobd` ;
CREATE SCHEMA IF NOT EXISTS `projetobd` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `projetobd` ;

-- -----------------------------------------------------
-- Table `gerente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gerente` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `gerente` (
  `Login` VARCHAR(45) NOT NULL ,
  `Senha` VARCHAR(45) NULL ,
  PRIMARY KEY (`Login`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE UNIQUE INDEX `Login_UNIQUE` ON `gerente` (`Login` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pessoa` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `pessoa` (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `CPF` VARCHAR(45) NOT NULL ,
  `gerente_Login` VARCHAR(45) NULL DEFAULT NULL ,
  `PNome` VARCHAR(45) NOT NULL ,
  `RG` INT(11) NULL ,
  `Rua` VARCHAR(45) NULL ,
  `Numero` INT(11) NULL ,
  `Bairro` VARCHAR(45) NULL ,
  `CEP` VARCHAR(45) NULL ,
  `TipoPessoa` ENUM('CLIENTE','MONITOR','GERENTE') NOT NULL ,
  `Telefone` VARCHAR(45) NOT NULL ,
  `Cidade` VARCHAR(45) NULL ,
  PRIMARY KEY (`id`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tema`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tema` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `tema` (
  `IdTema` VARCHAR(45) NOT NULL ,
  `Tnome` VARCHAR(45) NOT NULL ,
  PRIMARY KEY (`IdTema`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pacote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pacote` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `pacote` (
  `IdPacote` VARCHAR(45) NOT NULL ,
  `NomePacote` VARCHAR(45) NOT NULL ,
  `PrecoPacote` DOUBLE NOT NULL ,
  PRIMARY KEY (`IdPacote`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `localizacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `localizacao` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `localizacao` (
  `IdLocalizacao` VARCHAR(45) NOT NULL ,
  `CEP` VARCHAR(45) NOT NULL ,
  `Numero` INT(11) NOT NULL ,
  `Rua` VARCHAR(45) NOT NULL ,
  `Bairro` VARCHAR(45) NOT NULL ,
  `Cidade` VARCHAR(45) NOT NULL ,
  PRIMARY KEY (`IdLocalizacao`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `festa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `festa` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `festa` (
  `IDFesta` INT NOT NULL AUTO_INCREMENT ,
  `clienteCPF` VARCHAR(11) NOT NULL ,
  `IdTema` VARCHAR(11) NOT NULL ,
  `localizacaoCEP` VARCHAR(45) NOT NULL ,
  `IdPacote` VARCHAR(11) NOT NULL ,
  `DataInicio` DATETIME NOT NULL ,
  `DataFIm` DATETIME NULL ,
  `HoraInicio` TIME NOT NULL ,
  `Externo` TINYINT(1) NULL ,
  `QuantidadeConvidados` INT(11) NOT NULL ,
  `EstiloFesta` VARCHAR(45) NOT NULL ,
  PRIMARY KEY (`IDFesta`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
PACK_KEYS = DEFAULT;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `item` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `item` (
  `IDItem` VARCHAR(45) NOT NULL ,
  `NomeItem` VARCHAR(45) NOT NULL ,
  `QuantidadeTotal` INT(11) NOT NULL ,
  `PrecoUnidade` DOUBLE NOT NULL ,
  PRIMARY KEY (`IDItem`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pessoa_monitora_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pessoa_monitora_item` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `pessoa_monitora_item` (
  `pessoa_CPF` VARCHAR(11) NOT NULL ,
  `item_IDItem` INT NOT NULL ,
  PRIMARY KEY (`pessoa_CPF`, `item_IDItem`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pacote_contem_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pacote_contem_item` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `pacote_contem_item` (
  `chavePacote` VARCHAR(45) NOT NULL ,
  `chaveItem` VARCHAR(45) NOT NULL ,
  `nomePacote` VARCHAR(45) NOT NULL ,
  PRIMARY KEY (`chavePacote`, `chaveItem`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
USE `projetobd` ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
'
