/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import InterfaceDAO.GenericDAOInterface;
import controler.Pessoa;

import javax.swing.JOptionPane;

import entidadesDAO.FabricaDeDAO;

/**
 *
 * @author andreza
 */
public class Resultado extends javax.swing.JFrame {

    /**
     * Creates new form ResultadoCliente
     */
    private  String tipo; 
    private GenericDAOInterface daoAcessaDadosPessoas;// um DAO generico para acesso a dados de pessoas cadastradas.
    
   
   public Resultado(String nome, String cpf, String bairro, String telefone, String rua, String rg, String numero, String cep, String cidade, String categoriaPessoa)
   {
	   daoAcessaDadosPessoas = FabricaDeDAO.criarPessoaDAO();
	   initComponents();   
	   
	   this.textoNome.setText(nome);
	   this.textoCPF.setText(cpf);
	   this.textoBairro.setText(bairro);
	   this.textoTelefone.setText(telefone);
	   this.textoRua.setText(rua);
	   this.textoRG.setText(rg);
	   this.numeroTexto.setText(numero);
	   this.textoCep.setText(cep);
	   this.textoCidade.setText(cidade);
	   this.tipo = categoriaPessoa;
	   
	   this.textoBairro.setEnabled(true);
	   this.textoNome.setEnabled(false);
       this.textoCPF.setEnabled(false);
       this.textoCep.setEnabled(false);
       this.textoRG.setEnabled(false);
       this.textoTelefone.setEnabled(false);
       this.textoRua.setEnabled(false);
       this.numeroTexto.setEnabled(false);
       this.textoCidade.setEnabled(false);
       System.out.println(tipo);
       this.setVisible(true);
   }
   
   public Resultado() {
   	daoAcessaDadosPessoas = FabricaDeDAO.criarPessoaDAO();
   	initComponents();   
   }

    
    public String getTipo() {
        return tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public void setCep(String cep) {
        getTextoCep().setText(cep);
    }

    public void setCidadee(String cidade) {
        getTextoCidade().setText(cidade);
    }
    
    public void setCpf(String cpf) {
        getTextoCPF().setText(cpf);
    }

    public void setRua(String rua) {
        getTextoRua().setText(rua);        
    }

    public void setBairro(String bairro) {
        getTextoBairro().setText(bairro);              
    }

    public void setNumero(String numero) {
        getNumeroTexto().setText(numero);        
    }

    public void setRG(String RG) {        
        getTextoRG().setText(RG);
    }

    public void setTelefone(String telefone) {
        getTextoTelefone().setText(telefone);                
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeLabel = new javax.swing.JLabel();
        cpfLabel = new javax.swing.JLabel();
        textoNome = new javax.swing.JTextField();
        setTextoCPF(new javax.swing.JTextField());
        RGLabel = new javax.swing.JLabel();
        setTextoRG(new javax.swing.JTextField());
        bairroLabel = new javax.swing.JLabel();
        ruaLabel = new javax.swing.JLabel();
        setTextoBairro(new javax.swing.JTextField());
        jSeparator2 = new javax.swing.JSeparator();
        setTextoRua(new javax.swing.JTextField());
        RGLabel1 = new javax.swing.JLabel();
        setTextoCep(new javax.swing.JTextField());
        telefoneLabel = new javax.swing.JLabel();
        setTextoTelefone(new javax.swing.JTextField());
        editarButton = new javax.swing.JButton();
        excluir = new javax.swing.JButton();
        cidadelabel = new javax.swing.JLabel();
        setTextoCidade(new javax.swing.JTextField());
        ceplabel = new javax.swing.JLabel();
        setNumeroTexto(new javax.swing.JTextField());
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        fecharButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nomeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nomeLabel.setText("Nome");

        cpfLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cpfLabel.setText("CPF");

        getTextoNome().setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        getTextoCPF().setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        RGLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RGLabel.setText("RG");

        getTextoRG().setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        bairroLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bairroLabel.setText("Bairro");

        ruaLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ruaLabel.setText("Rua");

        getTextoBairro().setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        getTextoRua().setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        getTextoRua().addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoRuaActionPerformed(evt);
            }
        });

        RGLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RGLabel1.setText("Numero");

        getTextoCep().setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        telefoneLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        telefoneLabel.setText("Telefone");

        getTextoTelefone().setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        editarButton.setText("Editar");
        editarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarButtonActionPerformed(evt);
            }
        });

        excluir.setText("Excluir");
        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });

        cidadelabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cidadelabel.setText("Cidade");

        getTextoCidade().setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        ceplabel.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        ceplabel.setText("CEP");

        getNumeroTexto().setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        getNumeroTexto().addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroTextoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("Informacoes do Cliente");

        fecharButton.setText("Fechar");
        fecharButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(editarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bairroLabel)
                                    .addComponent(ruaLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(getTextoRua(), javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addComponent(getTextoCidade(), javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(getTextoBairro()))
                                        .addGap(32, 32, 32)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ceplabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(RGLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(34, 34, 34)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(getTextoCep())
                                            .addComponent(getNumeroTexto())
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(fecharButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))))))
                            .addComponent(cidadelabel))
                        .addGap(61, 61, 61))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cpfLabel)
                                        .addGap(241, 241, 241)
                                        .addComponent(RGLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(getTextoRG(), javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nomeLabel)
                                        .addGap(32, 32, 32)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(getTextoCPF(), javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(getTextoNome(), javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(telefoneLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(getTextoTelefone(), javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeLabel)
                    .addComponent(getTextoNome(), javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfLabel)
                    .addComponent(getTextoCPF(), javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getTextoRG(), javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RGLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefoneLabel)
                    .addComponent(getTextoTelefone(), javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ruaLabel)
                    .addComponent(getTextoRua(), javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bairroLabel)
                    .addComponent(getTextoBairro(), javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RGLabel1)
                    .addComponent(getNumeroTexto(), javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cidadelabel)
                    .addComponent(getTextoCidade(), javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ceplabel)
                    .addComponent(getTextoCep(), javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fecharButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(editarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoRuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoRuaActionPerformed

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
        // TODO add your handling code here:
        int resposta = JOptionPane.showConfirmDialog( null,"Tem certeza que quer excluir o cliente do sistema?","Confirmacao", JOptionPane.YES_NO_OPTION);
        if(resposta == JOptionPane.YES_OPTION){                            
            Pessoa p = (Pessoa) daoAcessaDadosPessoas.buscar(getTextoCPF().getText(),tipo);        
            daoAcessaDadosPessoas.remover(p);
            JOptionPane.showMessageDialog(this,"Cliente Removido");
            this.dispose();
        }       
    }//GEN-LAST:event_excluirActionPerformed

    private void editarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarButtonActionPerformed
        // TODO add your handling code here:                
        
        
        this.getTextoBairro().setEditable(true);               
        this.getTextoBairro().setEnabled(true); 
        this.getTextoCep().setEditable(true);        
        this.getTextoCep().setEnabled(true);
        this.getTextoTelefone().setEditable(true);
        this.getTextoTelefone().setEnabled(true);
        this.getTextoRua().setEditable(true);
        this.getTextoRua().setEnabled(true);
        this.getNumeroTexto().setEditable(true);
        this.getNumeroTexto().setEnabled(true);
        this.getTextoCidade().setEditable(true);
        this.getTextoCidade().setEnabled(true);
        fecharButton.setText("Salvar");                
    }//GEN-LAST:event_editarButtonActionPerformed

    private void fecharButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharButtonActionPerformed
        // TODO add your handling code here:
        if(fecharButton.getText().equals("Fechar")){            
            TelaInicial tela = TelaInicial.getInstance();    
            tela.setVisible(true);
            this.dispose();
        }
        else{            
            int resposta = JOptionPane.showConfirmDialog( null,"Tem certeza que quer editar?","Confirmacao", JOptionPane.YES_NO_OPTION);
            if(resposta == JOptionPane.YES_OPTION){                
                Pessoa p = (Pessoa)daoAcessaDadosPessoas.buscar(getTextoCPF().getText(),tipo);
                p.setBairro(getTextoBairro().getText());
                p.setCep(getTextoCep().getText());
                p.setCidade(getTextoCidade().getText());
                p.setCpf(getTextoCPF().getText());
                p.setNumero(Integer.parseInt(getNumeroTexto().getText()));
                p.setPnome(getTextoNome().getText());
                p.setRg(Integer.parseInt(getTextoRG().getText()));
                p.setRua(getTextoRua().getText());
                p.setTelefone(getTextoTelefone().getText()); 
                p.setTipoPessoa(tipo);
                daoAcessaDadosPessoas.atualizar(p);   
                JOptionPane.showMessageDialog(this,"Cliente Editado");
                this.dispose();
                
            }            
            
        }
    }//GEN-LAST:event_fecharButtonActionPerformed

    private void numeroTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroTextoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Resultado().setVisible(true);
            }
        });
    }
    public javax.swing.JTextField getTextoBairro() {
		return textoBairro;
	}

	public void setTextoBairro(javax.swing.JTextField textoBairro) {
		this.textoBairro = textoBairro;
	}
	public javax.swing.JTextField getTextoNome() {
		return textoNome;
	}

	public void setTextoNome(String textoNome) {
		this.textoNome.setText(textoNome);
	}
	public javax.swing.JTextField getTextoCPF() {
		return textoCPF;
	}

	public void setTextoCPF(javax.swing.JTextField textoCPF) {
		this.textoCPF = textoCPF;
	}
	public javax.swing.JTextField getTextoCep() {
		return textoCep;
	}

	public void setTextoCep(javax.swing.JTextField textoCep) {
		this.textoCep = textoCep;
	}
	public javax.swing.JTextField getTextoRG() {
		return textoRG;
	}

	public void setTextoRG(javax.swing.JTextField textoRG) {
		this.textoRG = textoRG;
	}
	public javax.swing.JTextField getTextoTelefone() {
		return textoTelefone;
	}

	public void setTextoTelefone(javax.swing.JTextField textoTelefone) {
		this.textoTelefone = textoTelefone;
	}
	public javax.swing.JTextField getTextoRua() {
		return textoRua;
	}

	public void setTextoRua(javax.swing.JTextField textoRua) {
		this.textoRua = textoRua;
	}
	public javax.swing.JTextField getTextoCidade() {
		return textoCidade;
	}

	public void setTextoCidade(javax.swing.JTextField textoCidade) {
		this.textoCidade = textoCidade;
	}
	public javax.swing.JTextField getNumeroTexto() {
		return numeroTexto;
	}

	public void setNumeroTexto(javax.swing.JTextField numeroTexto) {
		this.numeroTexto = numeroTexto;
	}
	// Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RGLabel;
    private javax.swing.JLabel RGLabel1;
    private javax.swing.JLabel bairroLabel;
    private javax.swing.JLabel ceplabel;
    private javax.swing.JLabel cidadelabel;
    private javax.swing.JLabel cpfLabel;
    private javax.swing.JButton editarButton;
    private javax.swing.JButton excluir;
    private javax.swing.JButton fecharButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JTextField numeroTexto;
    private javax.swing.JLabel ruaLabel;
    private javax.swing.JLabel telefoneLabel;
    private javax.swing.JTextField textoBairro;
    private javax.swing.JTextField textoCPF;
    private javax.swing.JTextField textoCep;
    private javax.swing.JTextField textoCidade;
    private javax.swing.JTextField textoNome;
    private javax.swing.JTextField textoRG;
    private javax.swing.JTextField textoRua;
    private javax.swing.JTextField textoTelefone;
    // End of variables declaration//GEN-END:variables


	public javax.swing.JLabel getNomeLabel() {
		return nomeLabel;
	}

	public void setNome(String nome) {
		this.nomeLabel.setText(nome);
	}
}
